backend:
  name: test-repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Сайт"
    files:
      - file: "data/site.json"
        label: "Главная"
        name: "home"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }