backend:
  name: github
  repo: "Me1ky/autoservice-detali_mashin35"
  branch: main
  client_id: "Ov23li0sTCsxyZ4xqmdp"
  auth_endpoint: "https//decap-cms-oauth-liart.vercel.app/auth"

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Сайт"
    files:
      - file: "data/site.json"
        label: "Главная"
        name: "homepage"
        fields:
          - label: "Заголовок"
            name: "title"
            widget: "string"
          - label: "Описание"
            name: "description"
            widget: "text"
          - label: "Фото"
            name: "image"
            widget: "image"