backend:
  name: github
  repo: me1ky/-35-
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Сайт"
    files:
      - file: "data/site.json"
        label: "Главная страница"
        name: "homepage"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Описание", name: "description", widget: "text" }
          - { label: "Фото", name: "image", widget: "image" }